// Code generated by scripts/generate-versions.mjs; DO NOT EDIT.

package outpost

var supported = Versions{
	Host:     "f858207161ba29c01c82f4674aef83d91b74480f",
	SDK:      "1.0.0+outpost.5",
	Plugin:   "0.5.0",
	Daemon:   "0.5.0",
	Protocol: 5,
}
